In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4]

In [3]:
type(lst)

list

In [4]:
lst2 =np.array(lst)

In [5]:
lst2

array([1, 2, 3, 4])

In [6]:
type(lst2)

numpy.ndarray

In [7]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(1,100,3)

array([  1. ,  50.5, 100. ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
 #normal distributiom 

In [21]:
np.random.rand(2,2)

array([[0.83645281, 0.34588498],
       [0.59208873, 0.01702924]])

In [22]:
#standard normal distribution

In [23]:
np.random.randn(3,3)

array([[-0.10238576, -0.11555053,  0.95521973],
       [-0.96545588,  1.78577226,  0.81836703],
       [-1.4644684 ,  0.85884392,  1.41136631]])

In [34]:
np.random.randint(1,101,3)

array([14, 85, 85])

In [35]:
np.random.randint(1,101,(2,2))

array([[91, 16],
       [81, 72]])

In [36]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:

np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [39]:
arr = np.arange(1,25)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [44]:
arr.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [64]:
arrr = arr.reshape(6,4)

In [65]:
arr.shape

(24,)

In [66]:
arrr.shape

(6, 4)

In [49]:
ranarr = np.random.randint(0,101,10)
ranarr

array([63, 59, 20, 32, 75, 57, 21, 88, 48, 90])

In [57]:
ranarr.max()


90

In [58]:
ranarr.argmax() #index for the max

9

In [51]:
ranarr.min()

20

In [59]:
ranarr.argmin() #index for min

2

In [60]:
ranarr.dtype

dtype('int32')

In [70]:
#### indexing and selection

In [79]:
arn = np.arange(1,10)

In [80]:
arn

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arn [3]

4

In [83]:
arn[1:5]

array([2, 3, 4, 5])

In [84]:
arn[:5]

array([1, 2, 3, 4, 5])

In [85]:
arn[5:]

array([6, 7, 8, 9])

In [86]:
#broadcasting

arn[0:5] =111

In [87]:
arn

array([111, 111, 111, 111, 111,   6,   7,   8,   9])

In [92]:
arn = np.arange(1,10)
arn

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
slice_of_arr = arn[:5]

In [102]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [103]:
slice_of_arr[:] = 99

In [104]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [105]:
arn

array([99, 99, 99, 99, 99,  6,  7,  8,  9])

In [ ]:
#effected the origianl one

In [106]:
true_copy = arn.copy()

In [107]:
true_copy

array([99, 99, 99, 99, 99,  6,  7,  8,  9])

In [108]:
true_copy[:] = 888

In [109]:
true_copy

array([888, 888, 888, 888, 888, 888, 888, 888, 888])

In [111]:
arn #no effect

array([99, 99, 99, 99, 99,  6,  7,  8,  9])

In [4]:
arr_2d = np.array([[1,2,3],[7,8,9],[5,6,4]])

In [5]:
arr_2d

array([[1, 2, 3],
       [7, 8, 9],
       [5, 6, 4]])

In [6]:
arr_2d.shape

(3, 3)

In [7]:
arr_2d[0]

array([1, 2, 3])

In [8]:
arr_2d[0][1] #by indexing

2

In [9]:
arr_2d[0,1]  #by row and column

2

In [10]:
arr_2d[:2,1:]

array([[2, 3],
       [8, 9]])

In [11]:
arra = np.arange(1,11)

In [12]:
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arra > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [14]:
bool_arr = arra>5

In [15]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [16]:
arra[bool_arr]

array([ 6,  7,  8,  9, 10])

In [17]:
arra[arra>5]

array([ 6,  7,  8,  9, 10])

In [18]:
#operations



In [25]:
array =np.arange(1,11)

In [34]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
array +2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
array -2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [29]:
array +array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
array/0 #not full error

C:\Users\navas\AppData\Local\Temp\ipykernel_11580\1069245135.py:1: RuntimeWarning: divide by zero encountered in true_divide
  array/0 #not full error


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [32]:
0/array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [37]:
array.sum()

55

In [38]:
array.mean()

5.5

In [39]:
array.std()

2.8722813232690143

In [40]:
array.max()

10

In [41]:
array.var()

8.25

In [42]:
arr2d = np.arange(0,25).reshape(5,5)

In [43]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr2d.shape

(5, 5)

In [45]:
arr2d.sum()

300

In [47]:
arr2d.sum(axis=0) #perform the opeartion accross rows 
                   #i.e sum of each column
    #

array([50, 55, 60, 65, 70])

In [50]:
arr2d.sum(axis=1) #perform the opeartion accross rows 
                   #i.e sum of each column

array([ 10,  35,  60,  85, 110])